# READLOG + GREPLOG

# HISTORY
export HISTFILESIZE=10000
export HISTSIZE=500
export HISTTIMEFORMAT="%F %T"
export HISTCONTROL=erasedups:ignoredups:ignorespace
shopt -s histappend

# COLOR
export TERM=xterm-256color
# 0  - No style         1  - Bold             2  - Dim                  3  - Italic       4  - Underline        
# 5  - Slow blink       6  - Rapid blink      7  - Reverse (fg-bg)      8  - Hidden       9  - Strikethrough
__hex_to_ansi() {
  local hex="${1#\#}" 
  local style="${2:-0}" # 
  local r=$((16#${hex:0:2}))
  local g=$((16#${hex:2:2}))
  local b=$((16#${hex:4:2}))
  printf '\e[%s;38;2;%d;%d;%dm' "$style" "$r" "$g" "$b"
}

# PROMPT
PROMPT_COMMAND=__prompt_command 

__color() {
    local color="$1" 
    local text="$2"

    local col_0='\[\e[0m\]' 
    local col_ylw="\[$(__hex_to_ansi EFBD58 2)\]"
    local col_grn="\[$(__hex_to_ansi A5CD84 1)\]"
    local col_red="\[$(__hex_to_ansi F8747E 1)\]"
    local col_blu="\[$(__hex_to_ansi 8DC3F1 1)\]"
    local col_pur="\[$(__hex_to_ansi DEAEED 1)\]"

    local col_var="col_$color"

    printf "%b%s%b" "${!col_var}" "$text" "$col_0"
}

__trimmed_pwd() {
  local dir="${PWD/#$HOME/~}"
  icon_flask="$(printf "\xF3\xB0\x82\x93")"
  icon_beach="$(printf "\xEF\x94\xA2")"

  if [[ $dir =~ ^/tmp/data/([^/]+)/data(/.*)?$ ]]; then 
    local base="${BASH_REMATCH[1]}"
    local rest="${BASH_REMATCH[2]}"
    [[ -z $rest ]] && rest=""
    dir="$icon_flask${base}${rest}"
  fi

  dir="${dir/\/tmp\/local\//$icon_beach/}"

  IFS='/' read -r -a parts <<< "$dir"
  local count=${#parts[@]}

  if (( count > 4 )); then
    printf ".../%s/%s\n" "${parts[count-2]}" "${parts[count-1]}"
  else
    printf "%s\n" "$dir"
  fi
}

__git_prompt() {
    if ! git rev-parse --is-inside-work-tree &>/dev/null; then
        return
    fi

    local branch=$(git symbolic-ref --short HEAD 2>/dev/null || git rev-parse --short HEAD 2>/dev/null)

    local fish_icon="$(printf "\xEE\xB9\x81")"
    local water_icon="$(printf "\xF3\xB0\x96\x8C")"

    local unpushed_commit=0
    if git rev-parse --abbrev-ref --symbolic-full-name @{u} &>/dev/null; then
        unpushed_commit=$(git rev-list --count @{u}..HEAD 2>/dev/null)
    fi

    local dirty=0
    [[ -n $(git status --porcelain 2>/dev/null) ]] && dirty=1

    local dirty_flag=""
    local commit_flag=""
    if (( unpushed_commit > 0 )); then
        if (( unpushed_commit > 1 )); then
            commit_flag+=" $(__color grn $unpushed_commit$fish_icon)"
        else
            commit_flag+=" $(__color grn $fish_icon)"
        fi
    fi
    if [[ $dirty -ne 0 ]]; then
        dirty_flag+="$(__color blu $water_icon) "
    fi

    echo "(${dirty_flag}${branch}${commit_flag}) "
}

__prompt_command() {
    local ec=$?

    local arrow="><> "
    if [[ $ec -ne 0 ]]; then
        arrow="$(__color red "$arrow")"
    else
        arrow="$(__color blu "$arrow")"
    fi

    local prompt_user="$(__color pur "\u ")"
    local prompt_pwd="$(__color ylw "$(__trimmed_pwd) ")"
    local prompt_git="$(__git_prompt)"

    PS1="${arrow}${prompt_pwd}${prompt_user}${prompt_git}"
}
